# Generated by Django 3.0.5 on 2025-12-26 06:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appt_id', models.AutoField(primary_key=True, serialize=False, verbose_name='预约ID')),
                ('appt_time', models.DateTimeField(auto_now_add=True, verbose_name='预约时间')),
                ('arrival_time', models.DateTimeField(verbose_name='预计到达时间')),
                ('status', models.IntegerField(choices=[(0, '未就诊'), (1, '已完成'), (2, '已取消')], default=0, verbose_name='预约状态')),
            ],
            options={
                'verbose_name': '预约',
                'verbose_name_plural': '预约',
            },
        ),
        migrations.CreateModel(
            name='ClinicRoom',
            fields=[
                ('room_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='诊室编号')),
                ('location', models.CharField(max_length=50, verbose_name='诊室位置')),
            ],
            options={
                'verbose_name': '诊室',
                'verbose_name_plural': '诊室',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False, verbose_name='科室ID')),
                ('dept_name', models.CharField(max_length=50, unique=True, verbose_name='科室名称')),
                ('dept_desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='科室描述')),
            ],
            options={
                'verbose_name': '科室',
                'verbose_name_plural': '科室',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='医生姓名')),
                ('title', models.CharField(max_length=20, verbose_name='职称')),
                ('mobile', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='手机号格式错误', regex='^1[3-9]\\d{9}$')], verbose_name='联系电话')),
                ('work_status', models.CharField(choices=[('在职', '在职'), ('离职', '离职')], default='在职', max_length=10, verbose_name='工作状态')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.Department', verbose_name='所属科室')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '医生',
                'verbose_name_plural': '医生',
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False, verbose_name='就诊ID')),
                ('visit_time', models.DateTimeField(auto_now_add=True, verbose_name='就诊时间')),
                ('visit_status', models.IntegerField(choices=[(0, '就诊中'), (1, '已离院')], default=0, verbose_name='就诊状态')),
                ('symptom', models.CharField(blank=True, max_length=500, null=True, verbose_name='病情描述')),
                ('prescription', models.CharField(blank=True, max_length=500, null=True, verbose_name='处方信息')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.Appointment', verbose_name='关联预约')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.Doctor', verbose_name='接诊医生')),
            ],
            options={
                'verbose_name': '就诊记录',
                'verbose_name_plural': '就诊记录',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('pay_id', models.AutoField(primary_key=True, serialize=False, verbose_name='缴费ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='总金额')),
                ('medical_insurance', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='医保金额')),
                ('self_pay', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='自费金额')),
                ('pay_time', models.DateTimeField(auto_now_add=True, verbose_name='缴费时间')),
                ('pay_method', models.CharField(choices=[('现金', '现金'), ('微信', '微信'), ('支付宝', '支付宝'), ('医保', '医保')], max_length=10, verbose_name='缴费方式')),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clinic.MedicalRecord', verbose_name='关联就诊记录')),
            ],
            options={
                'verbose_name': '缴费记录',
                'verbose_name_plural': '缴费记录',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False, verbose_name='患者ID')),
                ('name', models.CharField(max_length=20, verbose_name='患者姓名')),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女'), ('其他', '其他')], max_length=2, verbose_name='性别')),
                ('id_card', models.CharField(max_length=18, unique=True, verbose_name='身份证号')),
                ('mobile', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='手机号格式错误', regex='^1[3-9]\\d{9}$')], verbose_name='联系电话')),
                ('birth_date', models.DateField(verbose_name='出生日期')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '患者',
                'verbose_name_plural': '患者',
            },
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.Patient', verbose_name='患者'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.ClinicRoom', verbose_name='就诊诊室'),
        ),
        migrations.AddField(
            model_name='clinicroom',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.Department', verbose_name='所属科室'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.Department', verbose_name='预约科室'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.Patient', verbose_name='患者'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False, verbose_name='排班ID')),
                ('schedule_date', models.DateField(verbose_name='排班日期')),
                ('time_slot', models.CharField(max_length=20, verbose_name='接诊时间段')),
                ('status', models.IntegerField(choices=[(0, '不可接诊'), (1, '可接诊')], default=1, verbose_name='排班状态')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.Doctor', verbose_name='医生')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.ClinicRoom', verbose_name='诊室')),
            ],
            options={
                'verbose_name': '排班',
                'verbose_name_plural': '排班',
                'unique_together': {('doctor', 'schedule_date', 'time_slot')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('patient', 'arrival_time', 'dept')},
        ),
    ]
