# Generated by Django 3.0.5 on 2025-12-26 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('patient', 'arrival_time')},
        ),
    ]
